// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef func_h
#define func_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern Fl_Button *calc_btn;
#include <FL/Fl_Input.H>
extern Fl_Input *input;
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *stx;
extern Fl_Value_Input *tox;
extern Fl_Value_Input *stepx;
extern Fl_Value_Input *sty;
extern Fl_Value_Input *toy;
extern Fl_Value_Input *stepy;
#endif
