// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "func.h"
#include <math.h>

static double D[1000][1000], X, Y, Z; 
static int Nx,Ny; 
extern double Val;
extern int WE;
char S[256];
extern char S[256];
extern "C" void init();
extern "C" void yyparse();

Fl_Button *calc_btn=(Fl_Button *)0;
static void cb_calc_btn(Fl_Button*, void*)
{
  int i,j;
  static int in=0;
  if(in==0)
    {
      init();
       in=1;
    }
  
  /*
  if(strcmp(S,"")==0)
    return;
  */

  for(i=0, Y=sty->value();Y<=toy->value();Y+=stepy->value(),i++)
  {
    printf("\n");
    for(j=0, X=stx->value();X<=tox->value();X+=stepx->value(),j++)
    {
      sprintf(S,"X=%lf\n",X);
      yyparse();
      //printf("%13.1lf",Val);

      sprintf(S,"Y=%lf\n",Y);
      yyparse();
      //printf("%13.1lf",Val);
      strcpy(S,input->value());
      strcat(S,"\n");
      yyparse();
            
      if(WE==1)
        calc_btn->color(FL_RED);
      else
        calc_btn->color(48);

      sprintf(S,"%lf",Val);
      printf("%13.2lf",Val);
      fflush(stdout);

      if((i<1000)&&(j<1000))
        D[i][j]=Val;
      if (j>=1000)
        break;
    }
      if (i>=1000)
        break;
  }
  
  Nx=j; Ny=i;
  printf("\nNx=%d Ny=%d\n",Nx,Ny);
  WE=0;
}

Fl_Input *input=(Fl_Input *)0;

Fl_Value_Input *stx=(Fl_Value_Input *)0;

Fl_Value_Input *tox=(Fl_Value_Input *)0;

Fl_Value_Input *stepx=(Fl_Value_Input *)0;

Fl_Value_Input *sty=(Fl_Value_Input *)0;

Fl_Value_Input *toy=(Fl_Value_Input *)0;

Fl_Value_Input *stepy=(Fl_Value_Input *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(425, 225);
    w = o; if (w) {/* empty */}
    { calc_btn = new Fl_Button(30, 30, 70, 25, "Calc");
    calc_btn->callback((Fl_Callback*)cb_calc_btn);
    } // Fl_Button* calc_btn
    { input = new Fl_Input(170, 30, 215, 25, "Func");
    } // Fl_Input* input
    { Fl_Group* o = new Fl_Group(100, 90, 385, 50);
      { stx = new Fl_Value_Input(175, 115, 45, 25, "From");
      } // Fl_Value_Input* stx
      { tox = new Fl_Value_Input(250, 115, 45, 25, "To");
      } // Fl_Value_Input* tox
      { stepx = new Fl_Value_Input(340, 115, 45, 25, "Step");
      } // Fl_Value_Input* stepx
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(100, 160, 295, 60);
      { sty = new Fl_Value_Input(175, 165, 45, 25, "From");
      } // Fl_Value_Input* sty
      { toy = new Fl_Value_Input(250, 165, 45, 25, "To");
      } // Fl_Value_Input* toy
      { stepy = new Fl_Value_Input(340, 165, 45, 25, "Step");
      } // Fl_Value_Input* stepy
      o->end();
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(15, 115, 70, 25, "X");
      o->box(FL_NO_BOX);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(15, 160, 70, 25, "Y");
      o->box(FL_NO_BOX);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
