// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef bc_h
#define bc_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *A[32];
extern Fl_Round_Button *B[32];
extern Fl_Round_Button *C[32];
#include <FL/Fl_Input.H>
extern Fl_Input *vA, *vB, *vC;
#include <FL/Fl_Button.H>
extern Fl_Button *Syst;
extern Fl_Button *Razr;
extern Fl_Button *Op;
#endif
