// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef calc_h
#define calc_h
#include <FL/Fl.H>
extern "C" void yyparse();
extern "C" void init(void);
extern char S[200]; 
extern double Val;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *input;
#include <FL/Fl_Button.H>
extern Fl_Button *calc_btn;
extern Fl_Input *result;
#include <FL/Fl_Browser.H>
extern Fl_Browser *history;
extern Fl_Button *off_btn;
extern Fl_Button *clear_btn;
extern Fl_Button *ac_btn;
extern Fl_Button *sin_btn;
extern Fl_Button *arc_btn;
extern Fl_Button *cos_btn;
extern Fl_Button *ln_btn;
extern Fl_Button *lg_btn;
extern Fl_Button *fact_btn;
extern Fl_Button *power_btn;
extern Fl_Button *sqrt_btn;
extern Fl_Button *lftbrk_btn;
extern Fl_Button *rghtbrk_btn;
extern Fl_Button *space_btn;
extern Fl_Button *d_btn;
extern Fl_Button *c_btn;
extern Fl_Button *b_btn;
extern Fl_Button *a_btn;
extern Fl_Button *seven_btn;
extern Fl_Button *eight_btn;
extern Fl_Button *nine_btn;
extern Fl_Button *four_btn;
extern Fl_Button *five_btn;
extern Fl_Button *six_btn;
extern Fl_Button *one_btn;
extern Fl_Button *two_btn;
extern Fl_Button *three_btn;
extern Fl_Button *multiply_btn;
extern Fl_Button *div_btn;
extern Fl_Button *plus_btn;
extern Fl_Button *minus_btn;
extern Fl_Button *equal_btn;
extern Fl_Button *dot_btn;
extern Fl_Button *zero_btn;
extern Fl_Button *del_btn;
extern Fl_Button *pi_btn;
extern Fl_Button *Ebig_btn;
extern Fl_Button *log_btn;
extern Fl_Button *tan_btn;
#endif
