// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef bcl_dis_h
#define bcl_dis_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *inputA;
extern Fl_Input *inputB;
extern Fl_Input *inputC;
#include <FL/Fl_Button.H>
extern Fl_Button *bitChanger;
extern Fl_Button *bitChanger;
#endif
