// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "bcl_dis.h"

Fl_Input *inputA=(Fl_Input *)0;

Fl_Input *inputB=(Fl_Input *)0;

Fl_Input *inputC=(Fl_Input *)0;

Fl_Button *bitChanger=(Fl_Button *)0;

Fl_Button *bitChanger=(Fl_Button *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1245, 675);
    w = o; if (w) {/* empty */}
    o->color((Fl_Color)23);
    { inputA = new Fl_Input(1060, 250, 155, 40);
    } // Fl_Input* inputA
    { inputB = new Fl_Input(1060, 375, 155, 40);
    } // Fl_Input* inputB
    { inputC = new Fl_Input(1070, 575, 155, 40);
    } // Fl_Input* inputC
    { bitChanger = new Fl_Button(280, 145, 95, 35, "16");
      bitChanger->color((Fl_Color)29);
      bitChanger->labelsize(18);
    } // Fl_Button* bitChanger
    { Fl_Button* o = new Fl_Button(0, 265, 80, 25, "A");
      o->box(FL_NO_BOX);
      o->labelsize(24);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(0, 380, 80, 40, "B");
      o->box(FL_NO_BOX);
      o->labelsize(24);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(0, 585, 80, 40, "C");
      o->box(FL_NO_BOX);
      o->labelsize(24);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(5, 330, 70, 20, "+");
      o->box(FL_NO_BOX);
      o->labelsize(24);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(440, 20, 345, 35, "\320\221\320\270\320\275\320\260\321\200\320\275\321\213\320\271 \320\272\
\320\260\320\273\321\214\320\272\321\203\320\273\321\217\321\202\320\276\321\
\200");
      o->box(FL_NO_BOX);
      o->labelsize(26);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(205, 80, 230, 50, "\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \321\200\
\320\260\320\267\321\200\321\217\320\264\320\275\320\276\321\201\321\202\321\
\214:");
      o->box(FL_NO_BOX);
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(710, 80, 305, 50, "\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \321\201\
\320\270\321\201\321\202\320\265\320\274\321\203 \321\201\321\207\320\270\321\
\201\320\273\320\265\320\275\320\270\321\217:");
      o->box(FL_NO_BOX);
      o->labelsize(18);
    } // Fl_Button* o
    { bitChanger = new Fl_Button(825, 145, 95, 35, "10");
      bitChanger->labelsize(18);
    } // Fl_Button* bitChanger
    { Fl_Button* o = new Fl_Button(30, 545, 105, 35, "\320\240\320\265\320\267\321\203\320\273\321\214\321\202\320\260\321\202:");
      o->box(FL_NO_BOX);
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(460, 450, 270, 45, "\320\222\321\213\320\261\320\265\321\200\320\270\321\202\320\265 \320\264\
\320\265\320\271\321\201\321\202\320\262\320\270\320\265:");
      o->box(FL_NO_BOX);
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(400, 495, 50, 35, "+");
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(460, 495, 50, 35, "-");
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(525, 495, 50, 35, "<<");
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(650, 495, 50, 35, "%");
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(715, 495, 50, 35, "~A");
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(585, 495, 50, 35, ">>");
      o->labelsize(18);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(65, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(65, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(199, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(334, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(469, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(604, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(739, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(874, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(1000, 385, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(125, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(240, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(330, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(415, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(505, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(595, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(685, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(775, 590, 25, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(80, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(95, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(110, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(125, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(140, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(155, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(170, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(185, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(200, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(215, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(230, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(245, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(260, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(275, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(290, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(305, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(320, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(335, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(350, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(365, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(380, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(395, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(410, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(425, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(440, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(455, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(470, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(485, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(500, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(515, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(530, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(545, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(560, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(575, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(590, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(605, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(620, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(635, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(650, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(665, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(680, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(695, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(710, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(725, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(740, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(755, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(770, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(785, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(800, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(815, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(830, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(845, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(860, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(875, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(890, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(905, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(920, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(935, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(950, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(965, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(980, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(995, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(1010, 265, 15, 25, "1");
      o->labelsize(16);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
